"""message

Revision ID: ae38a083af86
Revises: ba802e7a82bb
Create Date: 2024-07-03 10:15:16.715599

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae38a083af86'
down_revision = 'ba802e7a82bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
